---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    # AWS_ACCESS_KEY_ID
    - secure: "nutZgqYqU9GfwqwNLBwSCkmIZUvDBrISd/1MO4IhtjifTUw9oCb2IkD\
      /dkuoc0nJgvFzMmzujbcpwekwtTaKTC3nTdr6fNbeET6c5MtigLo5mTGu2hchGil\
      14Jm/Z+cL5TE9wn+Q/dE4pakljvy13x/AJ5weLyqD4FWsl+aXALXIa5MXVL9iZve\
      2fF+i5gdke4MfAeI6AI3HtDLd8JH3Xc62cOtjmLzAPrtcYPUwItY282cVITl7PBe\
      QYKGSKnBF+Hw7UhjBjvHEkQBICLNSfyfcxTE1ARblx/RXyMv0gvt7UeKWqMKhGl3\
      lK5wJ/B3QexH0T2lhb3xZBXoIHS6SEotm4h62SkI+Yi+3TLbXIN+jxMqbZDSJyAg\
      NQx+ArWYBV0sPEmvAZXE4pfgzfVggn8MrBCRVPX5HzBz5gfcDicJk8S1Vm91raiV\
      gYs+ajHxp+EyHzXpQroCovsdJVYIhyB+XVcmq2Nibi8QuBLf9dnz1LtuY1nsAVBe\
      YAmvJXjonFVodPs1bqdrcHtKJhVEyLw+PffdV9wqCdTvnvA9y1AJhMYFmj6N7cQc\
      OfTvBPuprs5m8IseGX+rcOI9Yy1iR1p8qy0DT69BFOI0tJNg2HEu3ZhEzTU6vJI/\
      SKFazBHK4mLLORoBs+wuOhq+vGel7DF0DsUMO7QIIDxTTVpazztA="
    # AWS_SECRET_ACCESS_KEY
    - secure: "bmOzy3AowYfSKcjsDazTid0VH+2193NnOwnxQSrzEcZ5LjGxXtHpXc2\
      nQxwxSTRjk/YxJdczunhvBJqi9Z5VOuymwNpWI6vfHOIrnrof2eWbHIGmGF42RIz\
      NgAmlbJL4YOB6Q4xGIwIhBT6/UT/KrDnuMKbpZiNL8/yQrPh0NLEXt4DzXILilPS\
      mkjr7CQH9uv0ssJEnaWegStfZxcbtn6Wvdn6tqAUdiN0EryhK/reZakasoP4MkXa\
      KI5kug0nt7SJnjLRJWBtWTLF5mSroovK0QVeT4VkH0ct4g5fSn33uU7rtI8EZ1Ab\
      kj/oEuT/oLsHM3V547DxTcOKZqJjLn4GNDhXapkK+z8kz09D42S53dE50ns4fInp\
      8g2SlUS1LLc7HCVwDDCZuWxnWWQ4PNZ96Hzp9vnJJkR3L4iBaGE0U4eDNOXNrn05\
      jZI4YihSSVYLeyNh6o2kt+zdMa0elbYI+1WxWofL94xnjDoIlN9+2Qzt/HSvZwF5\
      c23e3SU/0N7aycpmfdc91qlqJlttdEAh92YNMnANaZS9nSPvhdqSMRuwi4E/UnNv\
      48ZF3YoB6FYrpsZG60SBfba2FLXb9y3gAhXw+Yhln1nyyW9MsuOMC+5a4ibQ4KDd\
      NXxrwMzjOP4KfvYpTmJiPeO+tEAeMoV5Fa9DEU1bPlpHhGG25ulU="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
