---
# tasks file for cyhy_dashboard

#
# Grab the ncats-webui code
#
- name: Create /var/cyhy/ncats-webui directory
  file:
    path: /var/cyhy/ncats-webui
    state: directory
    mode: 0760

- name: Download and untar the webui tarball
  # ansible-lint E208 gives an error if we don't specify the mode,
  # but we definitely don't want to do that here since it will
  # override the permissions on the files in the archive.
  unarchive:  # noqa 208
    src: "https://api.github.com/repos/cisagov/ncats-webui/tarball/develop"
    dest: /var/cyhy/ncats-webui
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
