---
#
# Grab the ncats-webui code
#
- name: Create /var/cyhy/ncats-webui directory
  ansible.builtin.file:
    path: /var/cyhy/ncats-webui
    state: directory
    mode: 0750

- name: Download and untar the ncats-webui tarball
  ansible.builtin.unarchive:
    src: https://api.github.com/repos/cisagov/ncats-webui/tarball/develop
    dest: /var/cyhy/ncats-webui
    remote_src: yes
    extra_opts:
      - --strip-components=1
