---
#
# Grab the ncats-webui code
#
- name: Create /var/cyhy/ncats-webui directory
  ansible.builtin.file:
    mode: 0750
    path: /var/cyhy/ncats-webui
    state: directory

- name: Download and untar the ncats-webui tarball
  ansible.builtin.unarchive:
    dest: /var/cyhy/ncats-webui
    extra_opts:
      - --strip-components=1
    remote_src: yes
    src: https://api.github.com/repos/cisagov/ncats-webui/tarball/improvement/migrate_to_node10
