---
#
# Grab the ncats-webui code
#
- name: Create the /var/cyhy/ncats-webui directory
  ansible.builtin.file:
    group: "{{ ncats_webui_file_owner_group | default(omit) }}"
    mode: 0750
    owner: "{{ ncats_webui_file_owner_username | default(omit) }}"
    path: /var/cyhy/ncats-webui
    state: directory

- name: Download and untar the ncats-webui tarball
  ansible.builtin.unarchive:
    dest: /var/cyhy/ncats-webui
    extra_opts:
      - --strip-components=1
    remote_src: yes
    src: https://api.github.com/repos/cisagov/ncats-webui/tarball/develop
